/**
 * Generated by `npm run gen:types` from schema/passclip-import.v1.schema.json.
 * Don't edit this file: change the schema, then run the script again.
 *
 * Some schema rules can't be written as TypeScript types, such as "boarding passes need
 * transit". They're left out here, and validation (src/lib/import/validate.ts) enforces them.
 */

/**
 * A date (2026-12-31) or a date-time as in dateTime.
 */
export type DateOrDateTime = string;
export type Latitude = number;
export type Longitude = number;
/**
 * ISO 8601 local date-time, ideally with a UTC offset: 2026-11-14T19:30:00+09:00. Without an offset, Passclip uses timeZone or asks the user.
 */
export type DateTime = string;
export type HexColor = string;
/**
 * Short notes about anything uncertain. Shown to the user before they add the pass.
 *
 * @maxItems 20
 */
export type Warnings = string[];

/**
 * Structured data that Passclip turns into Apple Wallet passes. Usually produced by an AI model using prompts/extract-to-passclip.txt, or written by hand. Version 1.1; version 1.0 documents are read too.
 */
export interface PassclipImport {
  /**
   * Format version: "1.1" (adds the ean13, code39, codabar and itf barcode types), or "1.0".
   */
  schemaVersion: "1.1" | "1.0";
  source?: Source;
  /**
   * One entry per ticket, person, travel segment, card or coupon. Empty when nothing usable was found (explain why in warnings).
   *
   * @maxItems 20
   */
  passes: Pass[];
  warnings?: Warnings;
}
/**
 * Where the data came from. Used for the back of the pass and, later, for email import.
 */
export interface Source {
  kind?: "email" | "pdf" | "screenshot" | "webpage" | "manual" | "other";
  sender?: string;
  subject?: string;
  receivedAt?: DateOrDateTime;
}
export interface Pass {
  /**
   * Apple Wallet pass style. eventTicket: concerts, sports, theater, movies, conferences, museums. boardingPass: flights, trains, buses, ferries. storeCard: loyalty or membership cards with points or a balance. coupon: discounts, offers, promo codes. generic: anything else, such as gym or library cards, parking or reservations.
   */
  type: "eventTicket" | "boardingPass" | "storeCard" | "coupon" | "generic";
  /**
   * Main name: the event, the route (e.g. "Tokyo → Paris"), the card or the offer.
   */
  title: string;
  /**
   * Short second line, e.g. a tour name or "Membership".
   */
  subtitle?: string;
  /**
   * Who issued it: the venue, airline, rail company or shop.
   */
  organization?: string;
  /**
   * Accessibility description read by VoiceOver. Passclip generates one if missing.
   */
  description?: string;
  /**
   * Ticket holder, passenger or member name, as written.
   */
  holderName?: string;
  /**
   * Booking or order reference, as written.
   */
  confirmationCode?: string;
  /**
   * Ticket number, as written.
   */
  ticketNumber?: string;
  /**
   * Event start, or departure time for travel.
   */
  start?: string;
  /**
   * Event end, or arrival time for travel.
   */
  end?: string;
  /**
   * IANA time zone where the event or departure happens, e.g. Asia/Tokyo. Used when a time has no UTC offset, and for calendar events.
   */
  timeZone?: string;
  /**
   * A date (2026-12-31) or a date-time as in dateTime.
   */
  expires?: string;
  venue?: Place;
  seat?: Seat;
  transit?: Transit;
  membership?: Membership;
  offer?: Offer;
  price?: Money;
  barcode?: Barcode;
  /**
   * Useful information such as door times, bag rules or check-in instructions.
   */
  notes?: string;
  /**
   * Other useful details as label/value pairs. The first ones may appear on the front of the pass; the rest go on the back.
   *
   * @maxItems 10
   */
  extraFields?: Field[];
  /**
   * Files and links clipped to the pass. They appear as links on the back of the pass.
   *
   * @maxItems 10
   */
  attachments?: Attachment[];
  style?: Style;
  calendar?: Calendar;
  warnings?: Warnings;
}
/**
 * Where an event happens.
 */
export interface Place {
  name: string;
  address?: string;
  city?: string;
  country?: string;
  /**
   * Hall, room, screen or stage inside the venue.
   */
  room?: string;
  latitude?: Latitude;
  longitude?: Longitude;
}
export interface Seat {
  section?: string;
  row?: string;
  /**
   * Seat number, e.g. 12 or 34K.
   */
  number?: string;
  /**
   * Gate, door or entrance at a venue.
   */
  entrance?: string;
  /**
   * e.g. General admission or Standing.
   */
  description?: string;
}
/**
 * Travel details. Required for boarding passes.
 */
export interface Transit {
  mode: "air" | "train" | "bus" | "boat" | "other";
  /**
   * Airline or operator name.
   */
  carrier?: string;
  /**
   * Airline code, e.g. NH.
   */
  carrierCode?: string;
  /**
   * Flight, train or route number as printed, e.g. "NH 7" or "Express 503".
   */
  number?: string;
  from: Stop;
  to: Stop;
  boardingTime?: DateTime;
  gate?: string;
  platform?: string;
  boardingGroup?: string;
  /**
   * Travel class, e.g. Economy.
   */
  cabin?: string;
  /**
   * Train car or coach number.
   */
  car?: string;
}
/**
 * A departure or arrival point. Needs at least a code, name or city.
 */
export interface Stop {
  /**
   * Airport or station code as printed, e.g. HND.
   */
  code?: string;
  /**
   * Airport or station name.
   */
  name?: string;
  city?: string;
  terminal?: string;
  latitude?: Latitude;
  longitude?: Longitude;
}
export interface Membership {
  programName?: string;
  memberId?: string;
  tier?: string;
  since?: DateOrDateTime;
  points?: number;
  balance?: Money;
}
export interface Money {
  amount: number;
  /**
   * ISO 4217 code, e.g. JPY, USD, EUR.
   */
  currency: string;
}
export interface Offer {
  /**
   * Short benefit, e.g. "20% off".
   */
  headline?: string;
  /**
   * Promo code to type or show at checkout.
   */
  code?: string;
  terms?: string;
}
export interface Barcode {
  /**
   * The type of code. ean13, code39, codabar and itf show in Wallet on iOS 27 and later.
   */
  format: "qr" | "pdf417" | "aztec" | "code128" | "ean13" | "code39" | "codabar" | "itf";
  /**
   * The exact data inside the code. Must come from the source text or a real scan, never invented.
   */
  message: string;
  /**
   * Short text shown under the code, often the ticket number.
   */
  altText?: string;
}
export interface Field {
  label: string;
  value: string;
}
export interface Attachment {
  title: string;
  /**
   * https links only.
   */
  url: string;
  kind?: "pdf" | "image" | "link" | "map" | "other";
}
/**
 * Pass colors. Optional; Passclip picks readable defaults per pass type.
 */
export interface Style {
  backgroundColor?: HexColor;
  foregroundColor?: HexColor;
  labelColor?: HexColor;
}
/**
 * Calendar options. Optional; by default passes with a start time offer Add to calendar.
 */
export interface Calendar {
  add?: boolean;
  title?: string;
  /**
   * @maxItems 3
   */
  alertMinutesBefore?: number[];
}
