import { readFile } from "node:fs/promises";
import path from "node:path";
import Ajv2020 from "ajv/dist/2020";
import standaloneCode from "ajv/dist/standalone";
import { SCHEMA_PATH } from "./import-types";

export const VALIDATOR_PATH = path.resolve("src/lib/import/schema-validator.generated.ts");

// Ajv normally turns the schema into JavaScript at runtime, which a strict Content-Security-Policy
// blocks in the browser (docs/DECISIONS.md D8). This compiles it ahead of time instead.
const BANNER = `// @ts-nocheck
/* eslint-disable */
// Generated by \`npm run gen:types\` from schema/passclip-import.v1.schema.json. Don't edit this file.
// It's Ajv's validation code for the schema, compiled ahead of time so that the browser never has
// to run generated code (see docs/DECISIONS.md D8). Exports validateImport.
`;

// Ajv's one runtime helper for this schema, inlined so the file has no require() calls.
const UCS2_REQUIRE = 'require("ajv/dist/runtime/ucs2length").default';
const UCS2_FUNCTION = `
// String length in Unicode code points, as JSON Schema counts it (from ajv/dist/runtime/ucs2length, MIT).
function ucs2length(str) {
  const len = str.length;
  let length = 0;
  let pos = 0;
  let value;
  while (pos < len) {
    length++;
    value = str.charCodeAt(pos++);
    if (value >= 0xd800 && value <= 0xdbff && pos < len) {
      value = str.charCodeAt(pos);
      if ((value & 0xfc00) === 0xdc00) pos++;
    }
  }
  return length;
}
`;

/** Builds the contents of src/lib/import/schema-validator.generated.ts. */
export async function generateImportValidator(): Promise<string> {
  const schema = JSON.parse(await readFile(SCHEMA_PATH, "utf8"));
  // messages: false, because src/lib/import/messages.ts writes its own plain messages.
  const ajv = new Ajv2020({ strict: true, allErrors: true, messages: false, code: { source: true, esm: true, lines: true } });
  ajv.addSchema(schema, "import");
  const code = standaloneCode(ajv, { validateImport: "import" }).split(UCS2_REQUIRE).join("ucs2length");
  if (code.includes("require(")) {
    throw new Error("The generated validator needs another Ajv runtime helper. Inline it in scripts/lib/import-validator.ts.");
  }
  return `${BANNER}${code}\n${UCS2_FUNCTION}`;
}
