import { readFile } from "node:fs/promises";
import path from "node:path";
import { compile, type JSONSchema } from "json-schema-to-typescript";

// npm scripts and Vitest both run from the project root.
export const SCHEMA_PATH = path.resolve("schema/passclip-import.v1.schema.json");
export const TYPES_PATH = path.resolve("src/lib/import/types.ts");

const BANNER = `/**
 * Generated by \`npm run gen:types\` from schema/passclip-import.v1.schema.json.
 * Don't edit this file: change the schema, then run the script again.
 *
 * Some schema rules can't be written as TypeScript types, such as "boarding passes need
 * transit". They're left out here, and validation (src/lib/import/validate.ts) enforces them.
 */`;

/**
 * Conditional and combined rules that TypeScript can't express. Kept in the schema for
 * validation, removed before generating types (json-schema-to-typescript turns them into
 * duplicated intersection types).
 */
const RUNTIME_ONLY_KEYWORDS = new Set([
  "allOf",
  "anyOf",
  "oneOf",
  "not",
  "if",
  "then",
  "else",
  "dependentRequired",
  "dependentSchemas",
]);

function isSchemaObject(value: unknown): value is JSONSchema {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function stripRuntimeOnlyRules(schema: JSONSchema): JSONSchema {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(schema)) {
    if (RUNTIME_ONLY_KEYWORDS.has(key)) continue;
    if ((key === "properties" || key === "$defs") && isSchemaObject(value)) {
      // Maps of name → schema: the names are data, so only their schemas are cleaned.
      result[key] = Object.fromEntries(
        Object.entries(value).map(([name, sub]) => [
          name,
          isSchemaObject(sub) ? stripRuntimeOnlyRules(sub) : sub,
        ]),
      );
    } else if ((key === "items" || key === "additionalProperties") && isSchemaObject(value)) {
      result[key] = stripRuntimeOnlyRules(value);
    } else {
      result[key] = value;
    }
  }
  return result as JSONSchema;
}

/** Builds the contents of src/lib/import/types.ts from the import schema. */
export async function generateImportTypes(): Promise<string> {
  const schema = JSON.parse(await readFile(SCHEMA_PATH, "utf8")) as JSONSchema;
  return compile(stripRuntimeOnlyRules(schema), "PassclipImport", {
    bannerComment: BANNER,
    additionalProperties: false,
    strictIndexSignatures: true,
    // Plain arrays instead of one tuple type per allowed length; maxItems is checked by validation.
    maxItems: -1,
    unreachableDefinitions: false,
  });
}
